[general]
name = "polya-vector-field"
version = "0.1.2"

[build]
files = ["main.fix"]

[[dependencies]]
name = "cairo-fix"
git = { url = "https://github.com/tttmmmyyyy/fixlang-cairo.git" }

[[dependencies]]
name = "math"
git = { url = "https://github.com/tttmmmyyyy/fixlang-math.git" }

[[dependencies]]
name = "time"
git = { url = "https://github.com/tttmmmyyyy/fixlang-time.git" }

[[dependencies]]
name = "random"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }

[[dependencies]]
name = "minilib-math"
git = { url = "https://github.com/pt9999/fixlang-minilib-math.git" }
