[general]
name = "polya-vector-field"
version = "0.1.1"

[build]
files = [
    "main.fix",
    "fixlang_minilib/lib/math/complex.fix",
    "fixlang_minilib/lib/math/types.fix",
]

[[dependencies]]
name = "cairo-fix"
git = { url = "https://github.com/tttmmmyyyy/fixlang-cairo.git" }

[[dependencies]]
name = "math"
git = { url = "https://github.com/tttmmmyyyy/fixlang-math.git" }

[[dependencies]]
name = "time"
git = { url = "https://github.com/tttmmmyyyy/fixlang-time.git" }

[[dependencies]]
name = "random"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }
